// Generated by tools/generate_rep_handles.py from nte-dumper rep_layouts.json.
// NTE 1.3.10; preserves the existing hand-written layout files.
pub fn wire_handle(layout: &str, field: &str, declared: u32) -> u32 {
    let (previous, current) = match (layout, field) {
        ("HTPlayerCharacter", "self_ht_player_controller") => (33, 51),
        ("HTPlayerCharacter", "current_weapon") => (38, 56),
        ("HTPlayerCharacter", "server_ready_flag") => (55, 89),
        ("HTPlayerCharacter", "saved_player_state") => (62, 98),
        ("PlayerState", "strength_current") => (65, 63),
        ("PlayerState", "role_level") => (72, 70),
        ("PlayerState", "role_exp") => (73, 71),
        ("PlayerState", "equipped_players") => (78, 76),
        ("PlayerState", "curr_character_net_id_solt") => (82, 80),
        ("PlayerState", "curr_character_net_id_serial") => (83, 81),
        ("PlayerState", "avatar_id") => (129, 131),
        ("AbilitySystemComponent", "hp_current") => (57, 18),
        ("AbilitySystemComponent", "max_hp") => (58, 19),
        ("AbilitySystemComponent", "max_hp_temp") => (59, 20),
        ("AbilitySystemComponent", "satiety_change_time") => (61, 22),
        ("AbilitySystemComponent", "atk") => (62, 23),
        ("AbilitySystemComponent", "charge_current") => (63, 24),
        ("AbilitySystemComponent", "unbal_speed") => (67, 28),
        ("GameplayAbilitySpec", "gameplay_tags") => (14, 6),
        ("GameplayAbilitySpec", "replicated_instances") => (16, 7),
        _ => return declared,
    };
    assert!(
        declared == previous || declared == current,
        "{layout}.{field}: declaration changed; regenerate and review the wire profile"
    );
    current
}
