// Generated by tools/generate_rep_handles.py from nte-dumper net_cache.json.
pub const INITIAL_RPCS_FINISHED: u32 = 168;
pub const CLIENT_DATA_LAYER_RPC: u32 = 262;
pub const RELIABLE_QUEST_INFO: u32 = 368;
pub const RELIABLE_SUBMITTED_QUEST: u32 = 369;
