"""Generate NTE 1.3.10 wire handles without rewriting existing user layouts.

Usage: python tools/generate_rep_handles.py ../nte-dumper/out/reflection-current
The dump must include the corrected CPF_RepSkip handling in nte-dumper.
"""
import json
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parents[1]
dump = pathlib.Path(sys.argv[1])
layouts = {x['class']: x for x in json.loads((dump / 'rep_layouts.json').read_text())}
for path in dump.glob('struct-layout-*.json'):
    report = json.loads(path.read_text())
    layouts[report['class']] = report
# Class, Rust struct, Rust field, declared handle, exact UE leaf path.
bindings = [
    ('AHTPlayerCharacter', 'HTPlayerCharacter', 'self_ht_player_controller', 33, 'SelfHTPlayerController'),
    ('AHTPlayerCharacter', 'HTPlayerCharacter', 'current_weapon', 38, 'CurrentWeapon'),
    ('AHTPlayerCharacter', 'HTPlayerCharacter', 'server_ready_flag', 55, 'ServerReadyFlag'),
    ('AHTPlayerCharacter', 'HTPlayerCharacter', 'saved_player_state', 62, 'SavedPlayerState'),
    ('AHTPlayerState', 'PlayerState', 'strength_current', 65, 'StrengthCurrent'),
    ('AHTPlayerState', 'PlayerState', 'role_level', 72, 'RoleLevel'),
    ('AHTPlayerState', 'PlayerState', 'role_exp', 73, 'RoleExp'),
    ('AHTPlayerState', 'PlayerState', 'equipped_players', 78, 'EquippedPlayers'),
    ('AHTPlayerState', 'PlayerState', 'curr_character_net_id_solt', 82, 'CurrCharacterNetID.solt'),
    ('AHTPlayerState', 'PlayerState', 'curr_character_net_id_serial', 83, 'CurrCharacterNetID.serial'),
    ('AHTPlayerState', 'PlayerState', 'avatar_id', 129, 'CurAvatar.Id'),
    ('UHTAbilitySystemComponent', 'AbilitySystemComponent', 'hp_current', 57, 'HPCurrent'),
    ('UHTAbilitySystemComponent', 'AbilitySystemComponent', 'max_hp', 58, 'MaxHP'),
    ('UHTAbilitySystemComponent', 'AbilitySystemComponent', 'max_hp_temp', 59, 'MaxHPTemp'),
    ('UHTAbilitySystemComponent', 'AbilitySystemComponent', 'satiety_change_time', 61, 'SatietyChangeTime'),
    ('UHTAbilitySystemComponent', 'AbilitySystemComponent', 'atk', 62, 'Atk'),
    ('UHTAbilitySystemComponent', 'AbilitySystemComponent', 'charge_current', 63, 'ChargeCurrent'),
    ('UHTAbilitySystemComponent', 'AbilitySystemComponent', 'unbal_speed', 67, 'UnbalSpeed'),
    ('GameplayAbilitySpec', 'GameplayAbilitySpec', 'gameplay_tags', 14, 'DynamicAbilityTags'),
    ('GameplayAbilitySpec', 'GameplayAbilitySpec', 'replicated_instances', 16, 'ReplicatedInstances'),
]
lines = [
    '// Generated by tools/generate_rep_handles.py from nte-dumper rep_layouts.json.',
    '// NTE 1.3.10; preserves the existing hand-written layout files.',
    'pub fn wire_handle(layout: &str, field: &str, declared: u32) -> u32 {',
    '    let (previous, current) = match (layout, field) {',
]
report = []
for cls, rust, field, old, path in bindings:
    matches = [leaf for entry in layouts[cls]['entries'] for leaf in entry['leaves']
               if leaf['path'] == path]
    if len(matches) != 1:
        raise ValueError(f'{cls}.{path}: expected one leaf, found {len(matches)}')
    new = matches[0]['handle']
    report.append(dict(layout=rust, field=field, declared=old, wire=new, path=path))
    lines.append(f'        ("{rust}", "{field}") => ({old}, {new}),')
lines += [
    '        _ => return declared,',
    '    };',
    '    assert!(declared == previous || declared == current,',
    '        "{layout}.{field}: declaration changed; regenerate and review the wire profile");',
    '    current',
    '}',
]
(root / 'lib/codegen/src/generated_rep_handles.rs').write_text('\n'.join(lines) + '\n')
(dump / 'fadia-wire-handles.json').write_text(json.dumps(report, indent=2) + '\n')
for item in report:
    print(f"{item['layout']}.{item['field']}: {item['declared']} -> {item['wire']}")

cache = {x['class']: x for x in json.loads((dump / 'net_cache.json').read_text())}
rpc_names = {
    'INITIAL_RPCS_FINISHED': 'Client_InitialRPCsFinished',
    'RELIABLE_QUEST_INFO': 'ClientReliableQuestInfo',
    'RELIABLE_SUBMITTED_QUEST': 'ClientReliableSubmittedQuest',
}
rpc_lines = ['// Generated by tools/generate_rep_handles.py from nte-dumper net_cache.json.']
for constant, name in rpc_names.items():
    matches = [x for x in cache['AHTPlayerState']['fields'] if x['name'] == name]
    if len(matches) != 1 or matches[0].get('direction') != 'client':
        raise ValueError(f'Missing client RPC: {name}')
    rpc_lines.append(f'pub const {constant}: u32 = {matches[0]["index"]};')
(root / 'servers/game-server/src/logic/hotta/generated_rpc_indices.rs').write_text('\n'.join(rpc_lines) + '\n')
